'''
17677. lv2 [1차] 뉴스 클러스터링
https://school.programmers.co.kr/learn/courses/30/lessons/17677
'''

# J(A, B)는 두 집합의 교집합 크기를 두 집합의 합집합 크기로 나눈 값으로 정의
#  집합 A와 집합 B가 모두 공집합일 경우에는 나눗셈이 정의되지 않으니 따로 J(A, B) = 1로 정의

# 다중집합 A = {1, 1, 2, 2, 3}, 다중집합 B = {1, 2, 2, 4, 5}라고 하면, 
# 교집합 A ∩ B = {1, 2, 2}, 합집합 A ∪ B = {1, 1, 2, 2, 3, 4, 5}가 되므로, 
# 자카드 유사도 J(A, B) = 3/7, 약 0.42가 된다.

#  "AB"와 "Ab", "ab"는 같은 원소로 취급한다.

# 이때 영문자로 된 글자 쌍만 유효하고, 기타 공백이나 숫자, 특수 문자가 들어있는 경우는 그 글자 쌍을 버린다. 
# 예를 들어 "ab+"가 입력으로 들어오면, "ab"만 다중집합의 원소로 삼고, "b+"는 버린다.
import sys
from pprint import pprint
import math
from collections import Counter

input = sys.stdin.readline

def str_to_counter(s):
    n = len(s)
    s_list = list(s.lower())
    # print(s_list)
    arr = []
    for i in range(n-1):
        if s_list[i].isalpha() and s_list[i+1].isalpha():
            arr.append(''.join([s_list[i], s_list[i+1]]))
    return len(arr), Counter(arr)

def solution(str1, str2):
    # print()
    # print(str1, str2)
    len1, counter1 = str_to_counter(str1)
    len2, counter2 =str_to_counter(str2)
    # pprint(counter1)
    # pprint(counter2)

    if len1==len2==0:
        return 65536
    
    and_cnt = 0 # 교집합

    # 교집합 업데이트
    for k,v in counter1.items():
        # counter1의 key가 counter2에도 있으면
        # value의 최솟값 반환
        if k in counter2:
            and_cnt += min(v, counter2[k])
    # print(and_cnt)
    
    # 합집합 수 세기
    or_cnt = and_cnt + (len1-and_cnt) + (len2-and_cnt)
    # print(or_cnt)
    return  math.floor((and_cnt/or_cnt)*65536)

# 16384
print(solution('FRANCE', 'french'))

# 65536
print(solution('handshake', 'shake hands'))

# 43690
print(solution('aa1+aa2', 'AAAA12'))

# 65536
print(solution('E=M*C^2', 'e=m*c^2'))

# 공집합 케이스
print(solution('**', '12'))

# 최소 케이스
print(solution('aa', 'aa'))
print(solution('aa', 'ab'))
# 최대 케이스
print(solution('AKIUFGSOHTKIEXJXCYGBAOMZSAWORVOBNGVPLYYWGHNVIBGWKKDXXEVNGRDBPDEKDNFQXLGBNNRGKESFXCDMIHRZAVCXKYNUJMPJTQZHMCNMOZEEZDDTNXOVDYHTBEFWUGXHAHWUPLUVLQIXMZLNDMARRNEXQTYQATGPRLVPIYHIZMEAKLLBFZUKBYBTGPLAIVPGURYKFVWHKPCDVSGETMAYBTFXRZXBEBGOZGMXBUJQPNNWLHCDOKVKNOJJIBGVDMWFLTGKJBZXYXVUTCNSJKMBWVLHBOJRHKUITNSFUSZZGHCZDZZOVFJOBTJZAKKMHVTFNEDQTQTHJVXCMTUOLHJUFIWNYJARAXHPCSXAESKJIKHWUQIJQHMXWRCEZLQTFRIXUSYRMBCCQGJFLYOPQOBIPICJNTAURXAVQZFKOXEQJFCZNCBXAWWDICHQLXYDKZIZUOYJGRBDNFFCPMKZIBMKRTSJWEZFAPJTGRCXQDOJEJTXRNVRYOSWVNNHRNKENIUXZFUZPHGPIRJAUTUGACFPGZZLPBMPVWJTVRQYVVMGTOVXUJXOAQZICIUJZUAZMXOGXZVQNEKTVJMFPXZLAEUMZTRTUIPJTHOCVRFNHZCWSKNUTGOTQIGSRXSEVBOXYRUSDHURBJVVHNIOEIEUVFMUIURPFNABCCHDJRRMPSVTLMXMQFVQWNPVUQORDOTNBAKCDYRUILIRTXLFYXGOSGLJQFJAAOEAMRHKBUDFFVTPKHBMFNDDPPNEZUDWAEGGRVNYILXQZIFLHSBTVQLGZCVXOIIKFCFUIOJIJHSKEYGQVBXVBADYWNGGDVFRGQURTMXBCBKDUMHRXDMLQWRQWCWWMJUVVOLBFAEJRJDNWTKZXVYZOXCRVHDFLIUSUBINLTIXKEGBBTHMBFEXBGLXZMBOLYKOHURRJNVUDAVQTENGNJAZFSALKCBHCTXEVYXLJPJTBQSCRSBDYUGIZJZUUNTOSXUIUMUVUMIDMBHS', 'JAVEGEYVWFVIAUSTEYNKSZPLLQBOGFMOYGUZZFDIFJXZOOGGTTTWFHGAEDLCXDQAEYAKBWCNIMTPCXJFUZKHOQLOVENMLFHHHXWJMZGXGSIAOGXQLXCSZTSWPZJBHCMOIBUGZMNTCFFPXNRZHRSIVPSGJPZLRXNSFRGABEIWDXDTEYNPPVNHBJUBZFUNMDQILZHDTSSPNAPYOKCGKRBTGOYLQXHHKBSPSJYHPGLLVHPCWFLVKKQDRDVFZIPJKZVNBNXOEEPKFKAQQJOSLEPGNEYMGMSIQLBQHAXFTUDHRXHZJFFGESEMYGGXNTCMXGRFDGLFCMQNQLOHEMUVSQHWMFZQRTDFXCQDNJXIOVYSMTUTCTKTQGJHUREYBURJNMUSKMZWGIZCMAQWHCCWPSWKPOSASJJYWTAUMUFXJVHHDUYPYIHEGFWCKVXBQKJVUOGWCZZCTWCLPUMDZMOXPSKMCKADRUZEGFHVDEKBJIFKLZEEGQBQHIJNHLDPUZCZXCHIBSURDTHVEJGNPNVSKWRHGUHNIRHDUDJSALVEBIYNPGLAFMJMFSPRCODJQRCBIUDMILYNWOOOLXJDOQNKSYRRBJMPJACZFUMBSBPCDHDPBXPVONTHICSZHEAEWXCRWNUKQGVJHJOKWXUPNTMBOBGYTYUUIKONQQXSWVWZUAYCVLSJYXMXXEBCFZJKPMEEIMQUUFZIGIASXMVMPVZSNZSFECKYIZCSGHRTGNZXDWQODBIDGRFPUGSSAAJYUCNPHWAPRVDMGZPYJCCKAOVUYUHVIVMFPIBDEDFIZALPALSAQZVPEPHDBVKPTKUHLUCUQYYVTWHQVHBUFVIHSMPWTILCMPZUYYMXUPLJYWJHROAUIEAUNMZIVVTVRKJVRAQKBAMJVQOHVFUYIUXUFTUGPTZTHSVKBNIJDJCZGOLXJMWKDRUDAJHJNQLGOFAYGIXHGJOUGPKRDNIWWFRMHVEZQGZDUEEMOXXEXJJIFLVUKUFV'))
